[package]
name = "qlc"
version = "0.5.0"
authors = ["Eric Butler <eric.butler@notarize.com>"]
edition = "2018"
license = "MIT"
autotests = false

[[test]]
name = "qlc"
path = "tests/mod.rs"

[dependencies]
crossbeam-channel = "0.3"
graphql-parser = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = "2"
num_cpus = "1"

[dev-dependencies]
assert_cmd = "0.11"
predicates = "1"
assert_fs = "0.11"
